name: Simple POC Compiler

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019  # Version avec .NET Framework
    steps:
    - uses: actions/checkout@v4
        
    - name: Compile and run POC with .NET Framework
      run: |
        # Trouver le compilateur C# .NET Framework
        $cscPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe"
        if (-not (Test-Path $cscPath)) {
            $cscPath = "${env:WINDIR}\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
        }
        
        Write-Host "Utilisation du compilateur: $cscPath"
        
        # Compiler le POC
        & "$cscPath" /out:poc.exe poc.cs
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Compilation réussie!"
            Write-Host "=== EXÉCUTION DU POC ==="
            ./poc.exe
        } else {
            Write-Host "Erreur de compilation"
            exit 1
        }
