name: Compile POC with Docker

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: Build and run in Windows container
      run: |
        # Créer un Dockerfile temporaire
        @"
        FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
        WORKDIR /app
        COPY poc.cs .
        RUN csc /out:poc.exe poc.cs
        CMD ["poc.exe"]
        "@ | Out-File -FilePath Dockerfile -Encoding UTF8
        
        # Construire et exécuter
        docker build -t poc-builder .
        docker run --rm poc-builder > payload.txt
        
        # Afficher le résultat
        Write-Host "=== PAYLOAD GÉNÉRÉ ==="
        Get-Content payload.txt
        Write-Host "=== FIN ==="
        
    - name: Upload payload
      uses: actions/upload-artifact@v4
      with:
        name: docker-payload
        path: payload.txt
