name: Simple POC

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe poc.cs
        .\poc.exe
