name: Compile POC with .NET Framework

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
        
    - name: Compile POC with .NET Framework
      run: |
        # Chercher le compilateur C# dans différents emplacements
        $cscPaths = @(
            "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe",
            "${env:ProgramFiles}\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe",
            "${env:WINDIR}\Microsoft.NET\Framework64\v4.0.30319\csc.exe",
            "${env:WINDIR}\Microsoft.NET\Framework\v4.0.30319\csc.exe"
        )
        
        $cscPath = $null
        foreach ($path in $cscPaths) {
            if (Test-Path $path) {
                $cscPath = $path
                break
            }
        }
        
        if (-not $cscPath) {
            Write-Host "Compilateur C# non trouvé. Installation des Build Tools..."
            # Alternative : utiliser le compilateur en ligne
            Invoke-WebRequest -Uri "https://www.nuget.org/api/v2/package/Microsoft.Net.Compilers/4.0.1" -OutFile "compilers.zip"
            Expand-Archive "compilers.zip" -DestinationPath "compilers"
            $cscPath = "compilers\tools\csc.exe"
        }
        
        Write-Host "Utilisation du compilateur: $cscPath"
        
        # Compiler le POC avec les références nécessaires
        & "$cscPath" /target:exe /out:poc.exe /reference:"${env:WINDIR}\Microsoft.NET\Framework64\v4.0.30319\System.dll" /reference:"${env:WINDIR}\Microsoft.NET\Framework64\v4.0.30319\System.Core.dll" poc.cs
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "=== COMPILATION RÉUSSIE ==="
            Write-Host "=== EXÉCUTION DU POC ==="
            $output = ./poc.exe
            Write-Host "=== PAYLOAD GÉNÉRÉ ==="
            Write-Host $output
            Write-Host "=== LONGUEUR: $($output.Length) caractères ==="
            
            # Sauvegarder le payload
            $output | Out-File -FilePath "payload.txt" -Encoding UTF8
        } else {
            Write-Host "=== ERREUR DE COMPILATION ==="
            exit 1
        }
        
    - name: Upload payload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: exploit-payload
        path: payload.txt
        retention-days: 7
