name: Simple POC Compiler

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Compile and run POC
      run: |
        # Créer un projet temporaire
        dotnet new console -o temp --force
        
        # Copier le POC
        Copy-Item poc.cs temp/Program.cs -Force
        
        # Modifier le .csproj pour permettre BinaryFormatter
        @"
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <OutputType>Exe</OutputType>
            <TargetFramework>net8.0</TargetFramework>
            <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
          </PropertyGroup>
        </Project>
        "@ | Out-File temp/temp.csproj -Encoding UTF8
        
        # Compiler et exécuter
        cd temp
        dotnet run
